import '@/styles/globals.scss';
import type { Metadata } from 'next';
import Header from './_layout/Header/Header';

export const metadata: Metadata = {
	title: 'Dev Quiz 🕹',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
